routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ActiveMemberController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::controller(LandingPageController::class)->group(function () {
    Route::get("/", "landingPage")->name("landing");
<<<<<<< routes/web.php
    Route::get("/webinars", "webinars")->middleware("login")->name("webinars");
=======
>>>>>>> routes/web.php
    Route::get("/webinar-form/{slug?}", "webinarFormPage")->middleware("login")->name("webinar");
});

Route::prefix("auth")->group(function () {
    Route::prefix("login")->name("login.")->group(function () {
        Route::controller(LoginController::class)->group(function () {
            Route::get("/", "loginPage")->name("page");
            Route::post("/", "loginPost")->name("post");
        });
    });

    Route::prefix("register")->name("register.")->group(function () {
        Route::get('/', function () {
            return view('register.register');
        })->name('page');
    });
});

Route::prefix("/dashboard")
    ->middleware("login")
    ->group(
        function () {
            Route::controller(DashboardController::class)->group(function () {
                Route::get("/", "dashboardPage")->name("dashboard");
                Route::post("/logout", "logout")->name("logout");
            });
<<<<<<< routes/web.php
=======

            Route::prefix("active-members")->name("active-members.")->group(function () {
                Route::controller(ActiveMemberController::class)->group(function () {
                    Route::get("/", "index")->name("index");
                    Route::post("/", "store")->name("store");
                    Route::get('/getData', 'getData')->name('getData');
                    Route::get('/create-or-update', 'createOrUpdate')->name('createOrUpdate');
                    Route::post('/create-or-update', 'createOrUpdatePost')->name('createOrUpdatePost');
                });
            });
>>>>>>> routes/web.php
        }
    );

resources/views/layouts/app.blade.php
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<script src="{{ asset('js/app.js') }}"></script>
<link href="{{ asset('vendor/flowbite/flowbite.css') }}" rel="stylesheet">
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200;400;500;600;700&display=swap" rel="stylesheet">
<link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://unpkg.com/tippy.js@6/animations/scale.css" />

resources/views/layouts/footer.blade.php
<footer class="bg-[#4A4A4A] text-white">
  <div class="container mx-auto py-16 px-6 sm:px-8 lg:px-16 xl:px-24">
      <div class="lg:flex lg:flex-row space-y-14 lg:space-y-0 lg:gap-y-12 lg:justify-between">
          <div class="flex flex-col gap-y-6 max-w-md">
              <div class="flex flex-row items-center gap-x-4">
                  <img class="w-16 rounded-xl" src="{{ asset('assets/ecode-logo.svg') }}" alt="Logo Ecode" class="rounded-lg h-8 w-8 cursor-pointer">
                  <h1 class="text-4xl font-semibold">E-Code</h1>
              </div>
              <div class="flex flex-col gap-y-4">
                  <p class="text-xl leading-relaxed sm:leading-relaxed">Himpunan Mahasiswa Teknik Informatika Politeknik Elektronika Negeri Surabaya</p>
                  <p class="">Jl. Raya ITS, Kec. Sukolilo, Surabaya 60111</p>
              </div>
          </div>
          <div class="flex flex-wrap gap-x-16">
              <div class="text-base mb-10">
                  <h4 class="font-semibold mb-6">TENTANG KAMI</h4>
                  <ul>
                      <li class="flex flex-col gap-y-3">
                          <a href="#">Sejarah</a>
                          <a href="#">Visi & Misi</a>
                          <a href="#">Prestasi</a>
                          <a href="#">Fasilitas</a>
                          <a href="#">Komunitas</a>
                      </li>
                  </ul>
              </div>
              <div class="text-base mb-10">
                  <h4 class="font-semibold mb-6">PRANALA LUAR</h4>
                  <ul>
                      <li class="flex flex-col gap-y-3">
                          <a href="#">Menristekdikti</a>
                          <a href="#">PENS</a>
                          <a href="#">DTIK PENS</a>
                          <a href="#">HIMIT PENS</a>
                      </li>
                  </ul>
              </div>
              <div class="text-base mb-10">
                  <h4 class="font-semibold mb-6">LEGAL</h4>
                  <ul>
                      <li class="flex flex-col gap-y-3">
                          <a href="#">Kebijakan Privasi</a>
                          <a href="#">Ketentuan dan Kondisi</a>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
      <div class="flex flex-col md:flex-row md:justify-between pt-10 gap-y-6 border-t border-gray">
          <p class="text-center">© 2023 E-Code. Crafted with 💙 from Surabaya</p>
          <div class="flex flex-row gap-x-6 justify-center">
              <a target="_blank" href="">
                  <img src="{{ asset('assets/tech-icon/facebook.svg') }}">
              </a>
              <a target="_blank" href="https://www.instagram.com/ecode.himit">
                  <img src="{{ asset('assets/tech-icon/instagram.svg') }}">
              </a>
              <a target="_blank" href="https://www.linkedin.com/company/e-code-himit-pens/about/">
                  <img src="{{ asset('assets/tech-icon/linkedin.svg') }}">
              </a>
              <a target="_blank" href="#">
                  <img src="{{ asset('assets/tech-icon/github-light.svg') }}">
              </a>
              <a target="_blank" href="https://gitlab.com/ecodehimit">
                  <img src="{{ asset('assets/tech-icon/gitlab.svg') }}">
              </a>
          </div>
      </div>
  </div>
</footer>

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="id">
  <head>
    @include('layouts.app')
    <title>Web E-Code</title>
  </head>

  @include('layouts.navbar')
  @yield("content")
  @include('layouts.footer')

  <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.min.js"></script>
  <script src="https://unpkg.com/tippy.js@6/dist/tippy-bundle.umd.js"></script>
  <script src="{{ asset('js/app.js') }}"></script>
</html>

resources/views/layouts/navbar.blade.php
<header>
    <div class="container mx-auto flex items-center justify-between px-6 sm:px-8 lg:px-16 xl:px-24">
        <div class="flex items-center gap-x-8">
            <a class="items-center" href="#">
                <img src="{{ asset('assets/ecode-logo.svg') }}" alt="Logo Ecode"
                    class="rounded-lg h-8 w-8 cursor-pointer" />
            </a>
            <nav class="nav items-center">
                <ul id="primary-navigation" data-visible="false"
                    class="primary-navigation flex gap-5 text-white sm:items-center sm:gap-0">
                    <li class="m-0 sm:mr-6 font-semibold"><a href="{{ route('login.page') }}">Home</a></li>
                    <li class="m-0 sm:mr-6"><a href="#">About</a></li>
                    <li class="m-0 sm:mr-6"><a href="#">Roadmap</a></li>
                    <li class="m-0 sm:mr-6"><a href="#">Webinars</a></li>
                    <li class="m-0 sm:mr-6"><a href="#">Verify Certificate</a></li>
                    <a class="sm:hidden py-2 px-6 rounded-xl bg-white text-dark font-semibold"
                        href="{{ route('login.page') }}">Login</a>
                </ul>
                <div class="nav-overlay"></div>
            </nav>
        </div>
        <button class="mobile-nav-toggle" aria-controls="primary-controls" aria-expanded="false">
            <span class="sr-only"></span>
        </button>
        <div class="h-full items-center hidden md:flex">
            <img src="{{ asset('assets/search.svg') }}" alt="search" class="w-5 h-5 mx-6 cursor-pointer">
            <a class="py-2 px-6 rounded-xl bg-white text-dark font-semibold" href="{{ route('login.page') }}">Login</a>
        </div>
    </div>
</header>